import assert from 'node:assert/strict';
import fs from 'node:fs';

const api=fs.readFileSync('netlify/functions/admin-platform.mts','utf8');
const org=fs.readFileSync('netlify/functions/_shared/organization.ts','utf8');
const page=fs.readFileSync('src/pages/admin/platform/index.astro','utf8');
const sandboxQa=fs.readFileSync('netlify/functions/_shared/tenant-sandbox-qa.ts','utf8');
const storage=fs.readFileSync('netlify/functions/_shared/tenant-storage.ts','utf8');
const health=fs.readFileSync('netlify/functions/_shared/system-health.ts','utf8');
const isolationWorkflow=fs.readFileSync('.github/workflows/venueloom-tenant-isolation-ci.yml','utf8');

assert.match(api,/VENUELOOM_SUPER_ADMIN_EMAILS/,'platform access must be explicitly allowlisted');
assert.match(api,/createPlatformSupportSession/,'support sessions must use control-plane audit storage');
assert.match(api,/readOnly:true/,'support mode must remain read-only');
assert.match(api,/ttlMinutes/,'support sessions must expire');
assert.match(api,/tenantMigrationAudit/,'platform detail must expose migration safety');
assert.match(api,/create-sandbox-tenant/,'safe Tenant #2 sandbox provisioning is required');
assert.match(api,/legacyCompatibility:false/,'sandbox safety response must confirm tenant-native storage');
assert.match(api,/stripeCheckoutStarted:false/,'sandbox provisioning must not start billing');
assert.match(api,/run-sandbox-leakage-test/,'platform API must expose the sandbox leakage runner');
assert.match(api,/run-sandbox-onboarding-test/,'platform API must expose the sandbox onboarding runner');
assert.match(api,/runChecks===true/,'sandbox creation must support immediate validation');
assert.doesNotMatch(api,/timezone:clean\(body\.timezone,100\)\|\|'Pacific\/Honolulu'/,'sandbox defaults must not hardcode Hawaiʻi timezone');
assert.match(sandboxQa,/koaCannotReadSandbox/,'sandbox QA must test sandbox → Koa leakage');
assert.match(sandboxQa,/sandboxCannotReadKoa/,'sandbox QA must test Koa → sandbox leakage');
assert.match(sandboxQa,/externalSideEffects:\{/,'onboarding QA must disclose external side effects');
assert.match(sandboxQa,/stripe:false/,'sandbox onboarding must not create billable Stripe activity');
assert.match(sandboxQa,/dns:false/,'sandbox onboarding must not mutate DNS');
assert.match(sandboxQa,/quickbooks:false/,'sandbox onboarding must not connect QuickBooks');
assert.match(sandboxQa,/runForEachTenant/,'sandbox QA must probe the runtime scheduled-job tenant iterator');
assert.match(sandboxQa,/schedulerProbeKey/,'scheduled-job probe must compare canonical tenant namespaces');
assert.match(storage,/legacyChecksum/,'migration audit must calculate legacy checksums');
assert.match(storage,/canonicalMirrorChecksum/,'migration audit must calculate mirror checksums');
assert.match(storage,/checksumMismatchCount/,'migration audit must report checksum mismatches');
assert.match(storage,/retirementStatus/,'migration audit must expose per-store retirement status');
assert.match(storage,/matchingEtag/,'migration audit must avoid downloading identical large Blob objects when etags already match');
assert.match(org,/support-sessions\/history/,'support sessions must be auditable');
assert.match(org,/expiresAt/,'support sessions must have an expiry');
assert.match(page,/Read-only support mode/,'UI must clearly identify support impersonation as read-only');
assert.match(page,/Create safe sandbox tenant/,'UI must expose isolated Tenant #2 provisioning');
assert.match(page,/Legacy Blob migration dashboard/,'Super Admin must show the detailed migration dashboard');
assert.match(page,/Run leakage test/,'Super Admin must expose the runtime leakage test');
assert.match(page,/Run onboarding QA/,'Super Admin must expose the sandbox onboarding journey');

assert.match(api,/reset-sandbox-tenant/,'platform API must support safe sandbox reset');
assert.match(api,/delete-sandbox-tenant/,'platform API must support safe sandbox deletion');
assert.match(api,/run-sandbox-onboarding-stage/,'platform API must support individual onboarding-stage reruns');
assert.match(api,/purgeSandboxTenantData/,'sandbox reset and deletion must purge tenant-scoped data');
assert.match(api,/deleteSandboxOrganizationControlPlane/,'sandbox deletion must remove disposable control-plane records');
assert.match(sandboxQa,/appendPlatformSandboxQaHistory/,'sandbox QA results must be archived outside disposable tenant data');
assert.match(sandboxQa,/SANDBOX_ONBOARDING_STAGES/,'sandbox onboarding stages must be explicitly allowlisted');
assert.match(page,/Reset sandbox data/,'Super Admin must expose sandbox reset');
assert.match(page,/Delete sandbox tenant/,'Super Admin must expose sandbox deletion');
assert.match(page,/Rerun selected stage/,'Super Admin must expose individual onboarding-stage reruns');
assert.match(page,/Historical QA reports/,'Super Admin must show retained sandbox QA history');
assert.match(page,/Leakage surfaces/,'Super Admin must show per-surface isolation results');
assert.match(api,/sandboxReadinessSnapshot/,'platform detail must evaluate the real-tenant readiness gate');
assert.match(api,/readGithubMainWorkflowSignal/,'readiness gate must consume a signed isolation-CI signal');
assert.match(api,/Credential separation/,'readiness gate must require credential separation');
assert.match(api,/Domain isolation/,'readiness gate must require domain isolation');
assert.match(api,/Storage isolation/,'readiness gate must require storage isolation');
assert.match(api,/Billing isolation/,'readiness gate must require billing isolation');
assert.match(page,/Tenant ready for real onboarding/,'Super Admin must expose the single readiness gate');
assert.match(page,/LOCKED — every readiness control must be green/,'readiness gate must remain locked until every control is green');
assert.match(page,/statusPill/,'readiness criteria must render strict green yellow red states');
assert.match(health,/readGithubMainWorkflowSignal/,'System Health must retain signed GitHub identity by workflow');
assert.match(health,/github\/main\/workflows\//,'signed workflow identities must use independent storage keys');
assert.match(isolationWorkflow,/push:/,'tenant isolation CI must run on main after merge');
assert.match(isolationWorkflow,/id-token: write/,'tenant isolation CI must be able to publish a signed OIDC result');
assert.match(isolationWorkflow,/Publish signed isolation-CI identity/,'main isolation CI must publish signed production readiness evidence');
assert.match(api,/action==='set-tenant-status'/,'tenant suspension and reactivation must be platform-managed');
assert.match(api,/Koa Tenant #1 suspension\/reactivation is blocked/,'Tenant #1 suspension must have a hard safety block');
assert.match(api,/action==='update-plan'/,'plan changes must be platform-managed');
assert.match(api,/subscription_items/,'active Stripe subscriptions must be updated at Stripe, not only locally');
assert.match(api,/action==='save-entitlements'/,'feature entitlements must be platform-managed');
assert.match(api,/view==='support-audit\.csv'/,'support audit CSV export must exist');
assert.match(api,/view==='usage'/,'platform usage metrics endpoint must exist');
assert.match(api,/action==='request-deletion'/,'organization deletion must use a staged request');
assert.match(api,/holdHours:24/,'organization deletion must have a minimum cooling-off period');
assert.match(api,/action==='finalize-deletion'/,'organization deletion must require a separate finalization action');
assert.match(api,/DELETE /,'final deletion must require destructive confirmation text');
assert.match(org,/deletion-requests\/history/,'deletion requests must be retained in the control-plane audit history');
assert.match(page,/Usage metrics/,'UI must expose platform-wide usage metrics');
assert.match(page,/Feature entitlements/,'UI must expose per-tenant feature entitlements');
assert.match(page,/Organization deletion safeguards/,'UI must explain deletion safeguards');

assert.doesNotMatch(api,/@netlify\/blobs/,'platform function must not bypass the control-plane/storage abstractions');

console.log('VenueLoom Super Admin regression test passed.');
