import assert from 'node:assert/strict';
import fs from 'node:fs';

const api=fs.readFileSync('netlify/functions/admin-platform.mts','utf8');
const org=fs.readFileSync('netlify/functions/_shared/organization.ts','utf8');
const page=fs.readFileSync('src/pages/admin/platform/index.astro','utf8');
const sandboxQa=fs.readFileSync('netlify/functions/_shared/tenant-sandbox-qa.ts','utf8');
const storage=fs.readFileSync('netlify/functions/_shared/tenant-storage.ts','utf8');

assert.match(api,/VENUELOOM_SUPER_ADMIN_EMAILS/,'platform access must be explicitly allowlisted');
assert.match(api,/createPlatformSupportSession/,'support sessions must use control-plane audit storage');
assert.match(api,/readOnly:true/,'support mode must remain read-only');
assert.match(api,/ttlMinutes/,'support sessions must expire');
assert.match(api,/tenantMigrationAudit/,'platform detail must expose migration safety');
assert.match(api,/create-sandbox-tenant/,'safe Tenant #2 sandbox provisioning is required');
assert.match(api,/legacyCompatibility:false/,'sandbox safety response must confirm tenant-native storage');
assert.match(api,/stripeCheckoutStarted:false/,'sandbox provisioning must not start billing');
assert.match(api,/run-sandbox-leakage-test/,'platform API must expose the sandbox leakage runner');
assert.match(api,/run-sandbox-onboarding-test/,'platform API must expose the sandbox onboarding runner');
assert.match(api,/runChecks===true/,'sandbox creation must support immediate validation');
assert.doesNotMatch(api,/timezone:clean\(body\.timezone,100\)\|\|'Pacific\/Honolulu'/,'sandbox defaults must not hardcode Hawaiʻi timezone');
assert.match(sandboxQa,/koaCannotReadSandbox/,'sandbox QA must test sandbox → Koa leakage');
assert.match(sandboxQa,/sandboxCannotReadKoa/,'sandbox QA must test Koa → sandbox leakage');
assert.match(sandboxQa,/externalSideEffects:\{/,'onboarding QA must disclose external side effects');
assert.match(sandboxQa,/stripe:false/,'sandbox onboarding must not create billable Stripe activity');
assert.match(sandboxQa,/dns:false/,'sandbox onboarding must not mutate DNS');
assert.match(sandboxQa,/quickbooks:false/,'sandbox onboarding must not connect QuickBooks');
assert.match(storage,/legacyChecksum/,'migration audit must calculate legacy checksums');
assert.match(storage,/canonicalMirrorChecksum/,'migration audit must calculate mirror checksums');
assert.match(storage,/checksumMismatchCount/,'migration audit must report checksum mismatches');
assert.match(storage,/retirementStatus/,'migration audit must expose per-store retirement status');
assert.match(org,/support-sessions\/history/,'support sessions must be auditable');
assert.match(org,/expiresAt/,'support sessions must have an expiry');
assert.match(page,/Read-only support mode/,'UI must clearly identify support impersonation as read-only');
assert.match(page,/Create safe sandbox tenant/,'UI must expose isolated Tenant #2 provisioning');
assert.match(page,/Legacy Blob migration dashboard/,'Super Admin must show the detailed migration dashboard');
assert.match(page,/Run leakage test/,'Super Admin must expose the runtime leakage test');
assert.match(page,/Run onboarding QA/,'Super Admin must expose the sandbox onboarding journey');
assert.doesNotMatch(api,/@netlify\/blobs/,'platform function must not bypass the control-plane/storage abstractions');

console.log('VenueLoom Super Admin regression test passed.');