export type ImportedBlogPost = {
  slug: string;
  title: string;
  excerpt: string;
  body: string;
  status: 'published';
  publishedAt: string;
  updatedAt: string;
  featuredImage?: string;
  author?: string;
  originalUrl?: string;
};

// This file is generated by scripts/migrate_wix_blog.py.
// It is intentionally committed so Netlify can bundle the imported posts
// without requiring a live Wix request at runtime.
export const wixBlogPosts: ImportedBlogPost[] = [];
